### ISSUE TITLE
rsshub里的配置怎么配置？

### ISSUE THREAD

**Issue by Freddy23317** [outloudvi/askme#1]
我按照Spotify 的要求分别搞好了SPOTIFY_CLIENT_ID
SPOTIFY_CLIENT_SECRET
SPOTIFY_REFRESHTOKEN
不知道下一步怎么弄，做了那个个人热门曲目也不是我的，求指点

**Comment by outloudvi** [comment]
>  不知道下一步怎么弄

在按照 [RSSHub 文档](https://docs.rsshub.app/zh/deploy/config#spotify)配置好这些环境变量之后，重启 RSSHub，Spotify 相关端点就应该能够使用。如果没有配置正确的话，这些端点返回的结果应该会[像官方实例一样](https://rsshub.app/spotify/top/artists)是空的。

> 做了那个个人热门曲目也不是我的

用户身份与获取 `SPOTIFY_REFRESHTOKEN` 时登录的帐号有关。如果个人热门曲目和你的帐号的不同，说明 refresh token 是其它账户的。请重新获取自己账户的 refresh token。

如果对此 RSSHub 路由有后续问题，可在 [RSSHub](https://github.com/DIYgod/RSSHub/issues) 的 issue 或 [discussion](https://github.com/DIYgod/RSSHub/discussions) 提问，这样的话其它人也可能可以帮助回答，并且回答也可以帮助到使用此 RSSHub 路由的其它用户。

**Comment by Freddy23317** [comment]
谢谢，不过我仍然没搞明白，https://rsshub.app/spotify/top/artists
这个我直接复制进rss阅读器没有订阅内容。我已经重启了rss reader了，求教

**Comment by outloudvi** [comment]
> https://rsshub.app/spotify/top/artists 这个我直接复制进rss阅读器没有订阅内容

rsshub.app 是官方 demo 实例，这个实例应该是没有配置 Spotify 相关环境变量的，所以它只返回空结果。

你需要自建一个 RSSHub 实例（例如，选择[这里](https://docs.rsshub.app/zh/deploy/)的其中一个部署平台），并在部署时的环境变量设定中添加这三个环境变量。
